### ISSUE TITLE
[BUG] Steamworks GameServer is not initialized

### ISSUE THREAD

**Issue by crashzk** [KitsuneLab-Development/CS2-SteamRestrict#15]
Receiving this error log:
```
2024-05-26 22:30:32.841 -03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Steamworks GameServer is not initialized.
   at Steamworks.InteropHelp.TestIfAvailableGameServer()
   at KitsuneSteamRestrict.SteamRestrictPlugin.CheckUserViolations(IntPtr handle, UInt64 authorizedSteamID)
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

**Comment by K4ryuu** [comment]
The issue has been solved by removing Steamworks completely from the project and using own solution for checking games. The update is going to be pushed with some other changes shortly.
